// <auto-generated />
namespace UniversityManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class version21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version21));
        
        string IMigrationMetadata.Id
        {
            get { return "201601261753185_version21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
