// <auto-generated />
namespace UniversityManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class version12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version12));
        
        string IMigrationMetadata.Id
        {
            get { return "201601251724463_version12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
